Pre commit setup
all-rit/ALL pull request #124
Opened 2022-09-07 17:03 UTC by AndreasLc1103

This MR is integrating a pre-commit tool to ALL stack. This enforces coding standards with prettier and esllint.

2022-09-07 17:31 UTC, Mster115 reviewed
Assuming everything looks and works the same it looks good, mostly lint fixes and setup anyways

2022-09-07 17:31 UTC, Mster115 approved these changes

2022-09-20 19:08 UTC, heathermoses requested changes
Breaking changes - needs review (let me know if Jaden or I can help since our machines were the ones this PR wasn't working for)

2022-09-26 19:19 UTC, heathermoses approved these changes
This looks good, great job!
Just need to update the setup instructions to include troubleshooting like we talked about today.

2022-09-28 18:15 UTC, merged