435 story webpage component connect webpage component to repair sections
all-rit/ALL pull request #457
Opened 2023-11-06 23:47 UTC by dm9965

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

2023-11-06 23:58 UTC, dm9965 commented
https://github.com/all-rit/ALL/assets/111752403/ecb4b6f1-9f8a-4283-aaef-b7140635a7cb

2023-11-07 00:48 UTC, AndreasLc1103 commented on client/src/components/exercise/lab9/Main.js
> +  // useEffect(() => {
remove commented out section

2023-11-07 14:01 UTC, AndreasLc1103 approved these changes
Looks good to me 🏁

2023-11-10 17:23 UTC, AndreasLc1103 approved these changes

2023-11-10 17:24 UTC, AndreasLc1103 requested changes
Please update branch with changes in `Development/Lab-9`

2023-11-29 18:03 UTC, AndreasLc1103 commented
this is closed because the code has been merged into other feature branches and will be reviewed then

2023-11-29 18:09 UTC, AndreasLc1103 commented
This story is going to be expanded to include the did you see it page, we didn't consider this in development and this can be included to quickly wrap up the story. This story will also pull in #461 to get some fixes for database connection and repair management fixes.

2023-11-29 21:22 UTC, merged