Fix material UI
all-rit/ALL pull request #577
Opened 2024-03-26 16:09 UTC by AndreasLc1103

To fix broken install issue and update material dependencies

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

2024-03-26 20:21 UTC, heathermoses requested changes
I tested this by pulling this branch and doing an `npm install` and the project worked for me. There's a few small issues with imports, but not breaking. Looks good to me otherwise

2024-03-26 20:21 UTC, heathermoses commented on client/src/components/exercise/lab3/helpers/StickyFooter.js
> +import Divider from "@mui/core/Divider";
I believe these should import from `@mui/material`

2024-03-26 20:21 UTC, heathermoses commented on client/src/components/exercise/lab4/components/CodeUpdateHeader.js
> +import Dialog from "@mui/core/Dialog";
These should import from `@mui/material`

2024-03-26 20:21 UTC, heathermoses commented on client/src/components/exercise/lab4/components/Header.js
> +import Grid from "@mui/core/Grid";
I think these should also import from `@mui/material`

2024-03-26 21:14 UTC, heathermoses approved these changes
LGTM

2024-03-27 22:42 UTC, dm9965 approved these changes
LGTM

2024-03-27 22:42 UTC, merged