562 story create graduation application form component
all-rit/ALL pull request #592
Opened 2024-04-10 15:22 UTC by apr8760

Jest testing to come.
To test, add  component to App.js -->(<GradApplication path="/Lab12/Exercise/*" user={state.main.user} />) and run.

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

2024-04-11 19:51 UTC, dm9965 approved these changes
Would like to see the red error handling message aligned with the input itself, however the functionality is correct. Approved.

![Screenshot 2024-04-11 at 3 44 49 PM](https://github.com/all-rit/ALL/assets/111752403/6b63ccae-4fe7-499d-ae26-94c40767961b)

2024-04-11 20:21 UTC, dm9965 requested changes
Set the red error handling to be aligned with the input box

![Screenshot 2024-04-11 at 3 44 49 PM](https://github.com/all-rit/ALL/assets/111752403/58768b99-8882-4ebf-a8de-6b212edd75a3)

2024-04-22 14:16 UTC, heathermoses approved these changes
This looks great! Great job on your first PR! :)

2024-04-22 14:16 UTC, heathermoses commented on client/src/components/exercise/lab12/GradApplication.js
> +/* eslint-disable no-unused-vars */
nit: remove this eslint line

2024-04-25 16:50 UTC, heathermoses approved these changes
I tested this by ensuring the error handling works and making sure tests pass. Looks good

2024-04-25 16:50 UTC, merged