565 lab 12 create repair
all-rit/ALL pull request #600
Opened 2024-04-21 21:39 UTC by dm9965

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

2024-04-22 11:57 UTC, AndreasLc1103 requested changes
Dev lab 12 needs dev rebase

2024-04-22 15:30 UTC, heathermoses approved these changes
Tested this by going through both repairs and ensuring error handling worked. LGTM! One small comment to remove console log

2024-04-22 15:30 UTC, heathermoses commented on client/src/components/body/Reading/Reading.js
> +    console.warn(user.userid);
nit: remove console log

2024-04-22 17:16 UTC, AndreasLc1103 requested changes
This needs another once over. Caught some moments of copy paste and if you don't fix them that they will become a problem. Also I think you need server test to validate things working so this needs more work.

2024-04-22 17:16 UTC, AndreasLc1103 commented on client/src/components/all-components/CodeBlock/Constants.js
> +export const sqlVariableRegex =
export them at the bottom like this 
`
export {
htmlTagRegex,
etc...
}
`

2024-04-22 17:16 UTC, AndreasLc1103 commented on client/src/components/body/Reading/Reading.js
>      UserLabService.complete_reading(labID);
remove

2024-04-22 17:16 UTC, AndreasLc1103 commented on client/src/components/exercise/lab12/pages/DatabaseRepair.js
> +const DatabaseRepair = () => {
Doc strings

2024-04-22 17:16 UTC, AndreasLc1103 commented on client/src/components/exercise/lab12/pages/FormRepair.js
> +
Doc strings

2024-04-22 17:16 UTC, AndreasLc1103 commented on client/src/components/exercise/lab12/pages/repairs/DatabaseRepairImplementation.js
> +import React from "react";
Doc strings describing intent

2024-04-22 17:16 UTC, AndreasLc1103 commented on client/src/components/exercise/lab12/pages/repairs/FormRepairImplementation.js
> +import React from "react";
same as last comment

2024-04-22 17:16 UTC, AndreasLc1103 commented on package.json
> +    "react-test-renderer": "^18.2.0",
move this to the dev dependencies

2024-04-22 17:16 UTC, AndreasLc1103 commented on server/controllers/lab12/ExerciseController.js
> +const ExerciseService = require('../../services/lab12/ExerciseService');
DON'T COPY AND PASTE AND SAY THIS IS DONE

2024-04-22 17:16 UTC, AndreasLc1103 commented on server/controllers/lab12/ExerciseController.js
> +      isAddressComplete: isAddressComplete,
CHANGE THESE

2024-04-22 17:16 UTC, AndreasLc1103 commented on server/database/models/lab12/Repair.js
> +// eslint-disable-next-line max-len
remove esflags

2024-04-22 17:19 UTC, AndreasLc1103 commented
Also merge in dev to this branch and the target branch

2024-04-22 17:24 UTC, dm9965 commented on client/src/components/body/Reading/Reading.js
>      UserLabService.complete_reading(labID);
Done

2024-04-22 17:28 UTC, dm9965 commented on client/src/components/all-components/CodeBlock/Constants.js
> +export const sqlVariableRegex =
done

2024-04-22 17:28 UTC, AndreasLc1103 commented
<img width="1458" alt="Screenshot 2024-04-22 at 1 28 17 PM" src="https://github.com/all-rit/ALL/assets/16628631/245d4afe-9a05-45a5-82b8-07c42cb77283">

2024-04-22 17:29 UTC, dm9965 commented on server/controllers/lab12/ExerciseController.js
> +      isAddressComplete: isAddressComplete,
done

2024-04-22 17:29 UTC, dm9965 commented on server/database/models/lab12/Repair.js
> +// eslint-disable-next-line max-len
done

2024-04-22 18:07 UTC, dm9965 commented on package.json
> +    "react-test-renderer": "^18.2.0",
done

2024-04-22 18:07 UTC, dm9965 commented on client/src/components/exercise/lab12/pages/repairs/FormRepairImplementation.js
> +import React from "react";
done

2024-04-22 18:07 UTC, dm9965 commented on client/src/components/exercise/lab12/pages/repairs/DatabaseRepairImplementation.js
> +import React from "react";
done

2024-04-22 18:07 UTC, dm9965 commented on client/src/components/exercise/lab12/pages/FormRepair.js
> +
done

2024-04-22 18:07 UTC, dm9965 commented on client/src/components/exercise/lab12/pages/DatabaseRepair.js
> +const DatabaseRepair = () => {
done

2024-05-07 13:53 UTC, AndreasLc1103 commented on server/controllers/lab12/RepairController.js
> +  if (userID === '' || section === '' || repair === '') {
you could also do something like this 
`if (!userID || !section || !repair)`

2024-05-07 13:54 UTC, AndreasLc1103 commented on server/controllers/lab12/RepairController.js
> +async function getRepair(req) {
add in an error case if there is nothing received

2024-05-07 14:39 UTC, AndreasLc1103 requested changes
Needs some more work but nothing crazy

2024-09-26 13:38 UTC, merged