652 create new labs page
all-rit/ALL pull request #669
Opened 2024-11-05 17:17 UTC by mpb8984

New labs page with ability to search and filter labs by category, difficulty and search phrases.

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

2024-11-05 17:58 UTC, heathermoses requested changes
This looks soooo good, just two small comments!

2024-11-05 17:58 UTC, heathermoses commented on client/src/components/body/labspage/LabsPage.js
> +/* eslint-disable no-inner-declarations */
Remove this and add prop types at the bottom

2024-11-05 17:58 UTC, heathermoses commented on client/src/components/body/labspage/LabsPage.js
> +                        </text>
Could we add just a little bit of padding below the category name?

![Screenshot 2024-11-05 at 12 57 15 PM](https://github.com/user-attachments/assets/e0593eb0-d573-4a0c-8860-ac8dd5eda142)

2024-11-06 17:35 UTC, heathermoses approved these changes
Good stuff Melissa!!

2024-11-06 19:10 UTC, dm9965 approved these changes
Looks great. We'll clean up the wonky lab card later. Awesome job.

2024-11-06 20:09 UTC, merged