Implement Lab Navigation Table and Update All Labs to Standard
all-rit/ALL pull request #675
Opened 2024-11-12 21:03 UTC by dm9965

# Story
#661 

## Work Completed
- Implemented Lab Navigation tab to affect all labs and properly navigate sections
- Updated all labs to fit new lab window
- Updated all labs to match current styling standards

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

2024-11-13 18:14 UTC, heathermoses requested changes
Looks beautifulllll, just a few really small things

2024-11-13 18:14 UTC, heathermoses commented on client/src/components/exercise/lab1/components/Content.js
> +      <main className="tw-h-full tw-p-6 tw-overflow-y-scroll">
I don't know if I should make a separate bug ticket or if this would be part of this story, but playing the Lab 1 exercise breaks in mobile

![Screenshot 2024-11-13 at 11 59 02 AM](https://github.com/user-attachments/assets/63955ca8-94c1-41f5-8cd1-0039072805c8)

2024-11-13 18:14 UTC, heathermoses commented on client/src/components/body/Reading/Reading.js
> +                      : " tw-body-styling-name tw-text-[#a3a3a3]"
Why did we change this to grey?

2024-11-13 18:14 UTC, heathermoses commented on client/src/components/exercise/lab2/LandingPage/landingPage.js
> +          button to begin the exercise
Center this

2024-11-13 18:14 UTC, heathermoses commented on client/src/components/exercise/lab3/pages/BeginnerExercise/AccessibleInstructions.js
> +          className="btn btn-primary tw-w-1/4 tw-h-[4rem] text-uppercase  leftButton"
Center this

2024-11-13 18:14 UTC, heathermoses commented on client/src/components/exercise/lab6/pages/Employer/HiringCandidate.js
> +        className={"tw-max-w-[20rem]"}
I know this isn't part of your PR but if you're in here, could you add some left padding to the confirm button?
![Screenshot 2024-11-13 at 12 27 02 PM](https://github.com/user-attachments/assets/13ce431c-1493-4568-a3cd-905a865f1fa6)

2024-11-14 15:47 UTC, dm9965 commented on client/src/components/exercise/lab3/pages/BeginnerExercise/AccessibleInstructions.js
> +          className="btn btn-primary tw-w-1/4 tw-h-[4rem] text-uppercase  leftButton"
Got it!

2024-11-14 15:47 UTC, dm9965 commented on client/src/components/exercise/lab2/LandingPage/landingPage.js
> +          button to begin the exercise
Done!

2024-11-14 16:43 UTC, dm9965 commented on client/src/components/exercise/lab6/pages/Employer/HiringCandidate.js
> +        className={"tw-max-w-[20rem]"}
Was unable to replicate this issue! Could you show me when you come in the office?

2024-11-14 17:16 UTC, heathermoses approved these changes
Just fix up the merge conflicts everything else LGTM!

2024-11-14 17:32 UTC, merged