About, Reading, Reinforcement Database Driven
all-rit/ALL pull request #87
Opened 2022-03-17 01:33 UTC by Mster115

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

2022-03-21 12:43 UTC, AndreasLc1103 requested changes

2022-03-21 12:43 UTC, AndreasLc1103 commented on client/src/assets/stylesheets/pages/CaseStudy.scss
> +    // flex-direction: column;
remove

2022-03-21 12:43 UTC, AndreasLc1103 commented on client/src/components/body/Reading/NonBulletList.jsx
> +
newline not needed

2022-03-21 12:43 UTC, AndreasLc1103 commented on client/src/components/body/Reading/NonBulletList.jsx
> +
same thing here

2022-03-21 12:43 UTC, AndreasLc1103 commented on client/src/components/body/lab/LabGeneration.js
> +      console.log("poop")
I want to say leave this but remove

2022-03-21 12:43 UTC, AndreasLc1103 commented on client/src/assets/stylesheets/pages/CaseStudy.scss
> +    // flex-direction: column;
Appear

2022-03-21 19:06 UTC, AndreasLc1103 commented on client/src/components/body/landingpage/citation/ProfileGeneration.js
> +    //const {}=props;
remove

2022-03-21 19:19 UTC, AndreasLc1103 commented on client/src/components/body/landingpage/citation/SlideSet.js
> +        // eslint-disable-next-line
do we need this?

2022-03-22 01:43 UTC, Stormkiller-01 reviewed
- Am now understanding as to why the lab1 - lab5 about, reading, and reinforcement files are now unneeded since by making the project more db driven, having general files that can encompass the settings needed for all 5 labs, via less files overall.

2022-03-22 14:01 UTC, AndreasLc1103 approved these changes

2022-03-22 14:02 UTC, merged